### ISSUE TITLE
 ### Responsive and accessible design (must-have)

### ISSUE THREAD

**Issue by Zalakshah786** [Zalakshah786/Typeracer#1]
To provide a tool for users to improve their typing speed.

**Comment by Zalakshah786** [comment]
**User goals:**

Users want to be able to:

- [ ] Measure and improve their typing speed.
- [ ] Know how to take the test.
- [ ] Easily take the test.
- [ ] Take a test relevant to their ability level.
- [ ] Use the test on different devices.
- [ ] See accurate results, including their words per minute (WPM).

**Comment by Zalakshah786** [comment]
**User story**

As a general user, I want the website to be responsive on various devices so that I can take the typing test on my preferred device.

**Acceptance Criteria:**

- [ ] The website layout adapts to different screen sizes (desktop, tablet, smartphone).

**Tasks:**

- [ ] Implement responsive design for the website to adapt to different screen sizes (desktop, tablet, smartphone)
